/******************************************************************************
 *                                                                         
 *               Copyright 2011 .
 *               All rights reserved.
 *
 *****************************************************************************/

namespace InstrumentDriver.Core.Common.IO
{

    #region Enumerations

    /// <summary>
    /// VISA PXIe address space enumeration
    /// </summary>
    public enum AddressSpace : short
    {
        PxiBar0 = AgVisa32.VI_PXI_BAR0_SPACE,
        PxiBar1 = AgVisa32.VI_PXI_BAR1_SPACE,
        PxiBar2 = AgVisa32.VI_PXI_BAR2_SPACE,
        PxiBar3 = AgVisa32.VI_PXI_BAR3_SPACE,
        PxiBar5 = AgVisa32.VI_PXI_BAR5_SPACE,
        LocalSpace = AgVisa32.VI_LOCAL_SPACE,
        ConfigSpace = AgVisa32.VI_PXI_CFG_SPACE,

    }

    /// <summary>
    /// Standard VISA events
    /// </summary>
    public enum VisaEvents
    {
        VI_EVENT_IO_COMPLETION = AgVisa32.VI_EVENT_IO_COMPLETION,
        VI_EVENT_TRIG = AgVisa32.VI_EVENT_TRIG,
        VI_EVENT_SERVICE_REQ = AgVisa32.VI_EVENT_SERVICE_REQ,
        VI_EVENT_CLEAR = AgVisa32.VI_EVENT_CLEAR,
        VI_EVENT_EXCEPTION = AgVisa32.VI_EVENT_EXCEPTION,
        VI_EVENT_GPIB_CIC = AgVisa32.VI_EVENT_GPIB_CIC,
        VI_EVENT_GPIB_TALK = AgVisa32.VI_EVENT_GPIB_TALK,
        VI_EVENT_GPIB_LISTEN = AgVisa32.VI_EVENT_GPIB_LISTEN,
        VI_EVENT_VXI_VME_SYSFAIL = AgVisa32.VI_EVENT_VXI_VME_SYSFAIL,
        VI_EVENT_VXI_VME_SYSRESET = AgVisa32.VI_EVENT_VXI_VME_SYSRESET,
        VI_EVENT_VXI_SIGP = AgVisa32.VI_EVENT_VXI_SIGP,
        VI_EVENT_VXI_VME_INTR = AgVisa32.VI_EVENT_VXI_VME_INTR,
        VI_EVENT_PXI_INTR = AgVisa32.VI_EVENT_PXI_INTR,
        VI_EVENT_TCPIP_CONNECT = AgVisa32.VI_EVENT_TCPIP_CONNECT,
        VI_EVENT_USB_INTR = AgVisa32.VI_EVENT_USB_INTR,
        VI_ALL_ENABLED_EVENTS = AgVisa32.VI_ALL_ENABLED_EVENTS,
    }

    public enum EventMechanism : short
    {
        QUEUE = AgVisa32.VI_QUEUE,
        HNDLR = AgVisa32.VI_HNDLR,
        SUSPEND_HNDLR = AgVisa32.VI_SUSPEND_HNDLR
    }


    /// <summary>
    /// Standard VISA status codes
    /// </summary>
    public enum StatusCodes
    {
        VI_SUCCESS = AgVisa32.VI_SUCCESS,
        VI_SUCCESS_EVENT_EN = AgVisa32.VI_SUCCESS_EVENT_EN,
        VI_SUCCESS_EVENT_DIS = AgVisa32.VI_SUCCESS_EVENT_DIS,
        VI_SUCCESS_QUEUE_EMPTY = AgVisa32.VI_SUCCESS_QUEUE_EMPTY,
        VI_SUCCESS_TERM_CHAR = AgVisa32.VI_SUCCESS_TERM_CHAR,
        VI_SUCCESS_MAX_CNT = AgVisa32.VI_SUCCESS_MAX_CNT,
        VI_SUCCESS_DEV_NPRESENT = AgVisa32.VI_SUCCESS_DEV_NPRESENT,
        VI_SUCCESS_TRIG_MAPPED = AgVisa32.VI_SUCCESS_TRIG_MAPPED,
        VI_SUCCESS_QUEUE_NEMPTY = AgVisa32.VI_SUCCESS_QUEUE_NEMPTY,
        VI_SUCCESS_NCHAIN = AgVisa32.VI_SUCCESS_NCHAIN,
        VI_SUCCESS_NESTED_SHARED = AgVisa32.VI_SUCCESS_NESTED_SHARED,
        VI_SUCCESS_NESTED_EXCLUSIVE = AgVisa32.VI_SUCCESS_NESTED_EXCLUSIVE,
        VI_SUCCESS_SYNC = AgVisa32.VI_SUCCESS_SYNC,
        VI_WARN_QUEUE_OVERFLOW = AgVisa32.VI_WARN_QUEUE_OVERFLOW,
        VI_WARN_CONFIG_NLOADED = AgVisa32.VI_WARN_CONFIG_NLOADED,
        VI_WARN_NULL_OBJECT = AgVisa32.VI_WARN_NULL_OBJECT,
        VI_WARN_NSUP_ATTR_STATE = AgVisa32.VI_WARN_NSUP_ATTR_STATE,
        VI_WARN_UNKNOWN_STATUS = AgVisa32.VI_WARN_UNKNOWN_STATUS,
        VI_WARN_NSUP_BUF = AgVisa32.VI_WARN_NSUP_BUF,
        VI_WARN_EXT_FUNC_NIMPL = AgVisa32.VI_WARN_EXT_FUNC_NIMPL,
        VI_ERROR_SYSTEM_ERROR = AgVisa32.VI_ERROR_SYSTEM_ERROR,
        VI_ERROR_INV_OBJECT = AgVisa32.VI_ERROR_INV_OBJECT,
        VI_ERROR_RSRC_LOCKED = AgVisa32.VI_ERROR_RSRC_LOCKED,
        VI_ERROR_INV_EXPR = AgVisa32.VI_ERROR_INV_EXPR,
        VI_ERROR_RSRC_NFOUND = AgVisa32.VI_ERROR_RSRC_NFOUND,
        VI_ERROR_INV_RSRC_NAME = AgVisa32.VI_ERROR_INV_RSRC_NAME,
        VI_ERROR_INV_ACC_MODE = AgVisa32.VI_ERROR_INV_ACC_MODE,
        VI_ERROR_TMO = AgVisa32.VI_ERROR_TMO,
        VI_ERROR_CLOSING_FAILED = AgVisa32.VI_ERROR_CLOSING_FAILED,
        VI_ERROR_INV_DEGREE = AgVisa32.VI_ERROR_INV_DEGREE,
        VI_ERROR_INV_JOB_ID = AgVisa32.VI_ERROR_INV_JOB_ID,
        VI_ERROR_NSUP_ATTR = AgVisa32.VI_ERROR_NSUP_ATTR,
        VI_ERROR_NSUP_ATTR_STATE = AgVisa32.VI_ERROR_NSUP_ATTR_STATE,
        VI_ERROR_ATTR_READONLY = AgVisa32.VI_ERROR_ATTR_READONLY,
        VI_ERROR_INV_LOCK_TYPE = AgVisa32.VI_ERROR_INV_LOCK_TYPE,
        VI_ERROR_INV_ACCESS_KEY = AgVisa32.VI_ERROR_INV_ACCESS_KEY,
        VI_ERROR_INV_EVENT = AgVisa32.VI_ERROR_INV_EVENT,
        VI_ERROR_INV_MECH = AgVisa32.VI_ERROR_INV_MECH,
        VI_ERROR_HNDLR_NINSTALLED = AgVisa32.VI_ERROR_HNDLR_NINSTALLED,
        VI_ERROR_INV_HNDLR_REF = AgVisa32.VI_ERROR_INV_HNDLR_REF,
        VI_ERROR_INV_CONTEXT = AgVisa32.VI_ERROR_INV_CONTEXT,
        VI_ERROR_QUEUE_OVERFLOW = AgVisa32.VI_ERROR_QUEUE_OVERFLOW,
        VI_ERROR_NENABLED = AgVisa32.VI_ERROR_NENABLED,
        VI_ERROR_ABORT = AgVisa32.VI_ERROR_ABORT,
        VI_ERROR_RAW_WR_PROT_VIOL = AgVisa32.VI_ERROR_RAW_WR_PROT_VIOL,
        VI_ERROR_RAW_RD_PROT_VIOL = AgVisa32.VI_ERROR_RAW_RD_PROT_VIOL,
        VI_ERROR_OUTP_PROT_VIOL = AgVisa32.VI_ERROR_OUTP_PROT_VIOL,
        VI_ERROR_INP_PROT_VIOL = AgVisa32.VI_ERROR_INP_PROT_VIOL,
        VI_ERROR_BERR = AgVisa32.VI_ERROR_BERR,
        VI_ERROR_IN_PROGRESS = AgVisa32.VI_ERROR_IN_PROGRESS,
        VI_ERROR_INV_SETUP = AgVisa32.VI_ERROR_INV_SETUP,
        VI_ERROR_QUEUE_ERROR = AgVisa32.VI_ERROR_QUEUE_ERROR,
        VI_ERROR_ALLOC = AgVisa32.VI_ERROR_ALLOC,
        VI_ERROR_INV_MASK = AgVisa32.VI_ERROR_INV_MASK,
        VI_ERROR_IO = AgVisa32.VI_ERROR_IO,
        VI_ERROR_INV_FMT = AgVisa32.VI_ERROR_INV_FMT,
        VI_ERROR_NSUP_FMT = AgVisa32.VI_ERROR_NSUP_FMT,
        VI_ERROR_LINE_IN_USE = AgVisa32.VI_ERROR_LINE_IN_USE,
        VI_ERROR_NSUP_MODE = AgVisa32.VI_ERROR_NSUP_MODE,
        VI_ERROR_SRQ_NOCCURRED = AgVisa32.VI_ERROR_SRQ_NOCCURRED,
        VI_ERROR_INV_SPACE = AgVisa32.VI_ERROR_INV_SPACE,
        VI_ERROR_INV_OFFSET = AgVisa32.VI_ERROR_INV_OFFSET,
        VI_ERROR_INV_WIDTH = AgVisa32.VI_ERROR_INV_WIDTH,
        VI_ERROR_NSUP_OFFSET = AgVisa32.VI_ERROR_NSUP_OFFSET,
        VI_ERROR_NSUP_VAR_WIDTH = AgVisa32.VI_ERROR_NSUP_VAR_WIDTH,
        VI_ERROR_WINDOW_NMAPPED = AgVisa32.VI_ERROR_WINDOW_NMAPPED,
        VI_ERROR_RESP_PENDING = AgVisa32.VI_ERROR_RESP_PENDING,
        VI_ERROR_NLISTENERS = AgVisa32.VI_ERROR_NLISTENERS,
        VI_ERROR_NCIC = AgVisa32.VI_ERROR_NCIC,
        VI_ERROR_NSYS_CNTLR = AgVisa32.VI_ERROR_NSYS_CNTLR,
        VI_ERROR_NSUP_OPER = AgVisa32.VI_ERROR_NSUP_OPER,
        VI_ERROR_INTR_PENDING = AgVisa32.VI_ERROR_INTR_PENDING,
        VI_ERROR_ASRL_PARITY = AgVisa32.VI_ERROR_ASRL_PARITY,
        VI_ERROR_ASRL_FRAMING = AgVisa32.VI_ERROR_ASRL_FRAMING,
        VI_ERROR_ASRL_OVERRUN = AgVisa32.VI_ERROR_ASRL_OVERRUN,
        VI_ERROR_TRIG_NMAPPED = AgVisa32.VI_ERROR_TRIG_NMAPPED,
        VI_ERROR_NSUP_ALIGN_OFFSET = AgVisa32.VI_ERROR_NSUP_ALIGN_OFFSET,
        VI_ERROR_USER_BUF = AgVisa32.VI_ERROR_USER_BUF,
        VI_ERROR_RSRC_BUSY = AgVisa32.VI_ERROR_RSRC_BUSY,
        VI_ERROR_NSUP_WIDTH = AgVisa32.VI_ERROR_NSUP_WIDTH,
        VI_ERROR_INV_PARAMETER = AgVisa32.VI_ERROR_INV_PARAMETER,
        VI_ERROR_INV_PROT = AgVisa32.VI_ERROR_INV_PROT,
        VI_ERROR_INV_SIZE = AgVisa32.VI_ERROR_INV_SIZE,
        VI_ERROR_WINDOW_MAPPED = AgVisa32.VI_ERROR_WINDOW_MAPPED,
        VI_ERROR_NIMPL_OPER = AgVisa32.VI_ERROR_NIMPL_OPER,
        VI_ERROR_INV_LENGTH = AgVisa32.VI_ERROR_INV_LENGTH,
        VI_ERROR_INV_MODE = AgVisa32.VI_ERROR_INV_MODE,
        VI_ERROR_SESN_NLOCKED = AgVisa32.VI_ERROR_SESN_NLOCKED,
        VI_ERROR_MEM_NSHARED = AgVisa32.VI_ERROR_MEM_NSHARED,
        VI_ERROR_LIBRARY_NFOUND = AgVisa32.VI_ERROR_LIBRARY_NFOUND,
        VI_ERROR_NSUP_INTR = AgVisa32.VI_ERROR_NSUP_INTR,
        VI_ERROR_INV_LINE = AgVisa32.VI_ERROR_INV_LINE,
        VI_ERROR_FILE_ACCESS = AgVisa32.VI_ERROR_FILE_ACCESS,
        VI_ERROR_FILE_IO = AgVisa32.VI_ERROR_FILE_IO,
        VI_ERROR_NSUP_LINE = AgVisa32.VI_ERROR_NSUP_LINE,
        VI_ERROR_NSUP_MECH = AgVisa32.VI_ERROR_NSUP_MECH,
        VI_ERROR_INTF_NUM_NCONFIG = AgVisa32.VI_ERROR_INTF_NUM_NCONFIG,
        VI_ERROR_CONN_LOST = AgVisa32.VI_ERROR_CONN_LOST,
        VI_ERROR_NPERMISSION = AgVisa32.VI_ERROR_NPERMISSION,
    }

    #endregion Enumerations
}